#  █████╗ ██████╗ ██████╗ ███████╗ █████╗ ██████╗  █████╗ ███╗   ██╗ ██████╗███████╗
# ██╔══██╗██╔══██╗██╔══██╗██╔════╝██╔══██╗██╔══██╗██╔══██╗████╗  ██║██╔════╝██╔════╝
# ███████║██████╔╝██████╔╝█████╗  ███████║██████╔╝███████║██╔██╗ ██║██║     █████╗
# ██╔══██║██╔═══╝ ██╔═══╝ ██╔══╝  ██╔══██║██╔══██╗██╔══██║██║╚██╗██║██║     ██╔══╝
# ██║  ██║██║     ██║     ███████╗██║  ██║██║  ██║██║  ██║██║ ╚████║╚██████╗███████╗
# ╚═╝  ╚═╝╚═╝     ╚═╝     ╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═══╝ ╚═════╝╚══════╝
#-----------------------------------------------------------------------------------



general {
    gaps_in = 4
    gaps_out = 8

    border_size = 2

    # Vibrant border for active window
    col.active_border = rgba(ff3db5ee) rgba(f5b8c6dd) 45deg
    col.inactive_border = rgba(f7d9e5aa)

    resize_on_border = true

    allow_tearing = false

    layout = dwindle
}

decoration {
    rounding = 8
    rounding_power = 2

    active_opacity = 0.94
    inactive_opacity = 0.82

    shadow {
        enabled = true
        range = 10
        render_power = 3
        color = rgba(cbb9c499)
    }

    blur {
        enabled = yes
        size = 10
        passes = 4
        new_optimizations = on
        ignore_opacity = on
        xray = false
        noise = 0.02
        contrast = 0.9
        brightness = 1.0
        vibrancy = 0.2
        vibrancy_darkness = 0.0
    }
}

# Blur waybar
layerrule = blur, waybar
layerrule = xray on, waybar
layerrule = ignorealpha 0.1, waybar
# Blur wlogout
layerrule = blur, logout_dialog
# Blur swaync
layerrule = blur, swaync-control-center
layerrule = blur, swaync-notification-window
layerrule = ignorealpha 0.1, swaync-control-center
layerrule = ignorealpha 0.1, swaync-notification-window
# Blur wofi
layerrule = blur, wofi
